export const GET_FORECAST_START = "GET_FORECAST_START";
export const GET_FORECAST_SUCCESS = "GET_FORECAST_SUCCESS";
export const GET_FORECAST_ERROR = "GET_FORECAST_ERROR";
export const PUSH_FORECAST_HISTORY = "PUSH_FORECAST_HISTORY";
